name = "gobbo-king-s2"
main = "index.js"
compatibility_date = "2026-06-12"

[[d1_databases]]
binding = "DB"
database_name = "goblin_rpg_s4"
database_id = "8792d45a-9204-450b-b541-9bea8a40cb56"

[triggers]
crons = [
  "0 * * * *",
  "* * * * *"
]

[vars]
RAID_ADMINS = "eryynftw,gobboherald"

[assets]
directory = "./chest-overlay"
binding = "ASSETS"